### ISSUE TITLE
[Suggestion] Integrate 2FA process for homelab server

### ISSUE THREAD

**Issue by cdeckel** [blaineventurine/home-automation-docker#1]
Hi, Seeing your impressive portfolio of docker integrations I have a suggest that might interest you as I'm doing pretty much of the same as you with many different docker containers and a home server setup and IOT via HA, one thing I'm trying to achieve is adding a 2FA (or even better UFA / FIDO2) authentication step to all these services over Traefik reverse proxy with Letsencrypt SSL / TLS certificates.
I've not yet gotten to doing so, but reading around it is doable, here are my suggestions to try:

Authelia: https://www.authelia.com
Keycloak: https://www.keycloak.org
Arno0x/TwoFactorAuth: https://github.com/Arno0x/TwoFactorAuth
gauth: https://github.com/gbraad/gauth

If you do get to it and publish your notes / guidelines that would be great 🥇

**Comment by blaineventurine** [comment]
You are more than welcome to fork this and implement those changes. I don't have a use case for 2FA quite yet, so it may be a while before I can get around to attempting that.
