### ISSUE TITLE
[Suggestion] Wikijs for documentation

### ISSUE THREAD

**Issue by Valefoth** [blaineventurine/home-automation-docker#2]
## Wikijs to document your home-automation

Hi @blaineventurine , you can use Wikijs to set up a documentation for all your stuff.
Wikijs is an open-source wiki software available on Docker too. 

The **best open documentation software** atm.

📖 [**Wikijs_link**](https://wiki.js.org/)
___

## Btw pretty neat setup 👍  ! 
**Looks very very great**, I'll try to do the same even if I require some knowledge especially with Traefik.

**Comment by blaineventurine** [comment]
I'm already using Bookstack.
